[rotary-context]
exten => 81,1,Answer() ; Call Dad
    same => n,GoSub(speak,s,1("Calling dad\!\!"))
    same => n,Set(CALLERID(all)="Me"<19787777777>)
    same => n,Dial(SIP/twilio/+12565121024)

exten => 82,1,Answer() ; Call Mom
    same => n,GoSub(speak,s,1("Calling mom\!\!"))
    same => n,Set(CALLERID(all)="Me"<19787777777>)
    same => n,Dial(SIP/twilio/+12125555555)

exten => 71,1,Answer() ; Play Banana Phone
    same => n,Playback(/var/lib/asterisk/sounds/en/BananPhn)
    same => n,Hangup()
    
exten => _9NXXNXXXXXX,1,Answer() ; 9 + <number>
    same => n,Set(CALLERID(all)="Rotary"<14157046737>)
    same => n,Dial(SIP/twilio/${EXTEN:1},120)
    same => n,Hangup()

[from-twilio]
exten => s,1,NoOp(Incoming Call)
    same => n,Dial(SIP/rotary)
    same => n,Hangup()
