[general]
minexpiry=605
defaultexpiry=605
qualify=yes
qualifyfreq=20
register => yourSipUser:yourSipPassword@yourSipSubdomain.sip.us1.twilio.com

[rotary]
type=friend
nat=force_rport,comedia
secret=rotary
host=dynamic
context=rotary-context
qualify=yes

[twilio-trunk](!)
type=peer
context=from-twilio
dtmfmode=rfc4733
canreinivite=no
insecure=port,invite

[twilio](twilio-trunk)
host=yourSipSubdomain.sip.us1.twilio.com
defaultuser=yourSipUser
remotesecret=yourSipPassword
permit=54.172.60.0/255.255.255.255
permit=54.172.60.3/255.255.255.255
permit=54.172.60.2/255.255.255.255
permit=54.172.60.1/255.255.255.255

[twilioip-1](twilio-trunk)
host=54.172.60.0

[twilioip-2](twilio-trunk)
host=54.172.60.1

[twilioip-3](twilio-trunk)
host=54.172.60.1

[twilioip-4](twilio-trunk)
host=54.172.60.2

[twilioip-5](twilio-trunk)
host=54.172.60.3
